language: node_js
dist: trusty
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - '11.0.0'
after_script: npm run coveralls:export
before_install:
  - nvm install stable
  - nvm use stable
install: npm install tulind --build-from-source && npm install
